INSERT INTO distributed (name, province_id, country_id) VALUES
('Great Eastern Drug Co.,Ltd.', 2, 219),
('Seven Stars Pharmaceutical Co.,Ltd.', 20, 219),
('Thai Nakorn Patana Co.,Ltd.', 24, 219),
('T.MAN PHARMA Co.,Ltd.', 2, 219),
('Greater Pharma Co.,Ltd.', 20, 219),
('Atlanta Medicare Co.Ltd.', 2, 219),
('Lerd Singh Pharmaceutical Fact.,Ltd.', 2, 219),
('A.N.B Laboratories Co.,Ltd.', 2, 219),
('Meiyume ManuFacturing Co.,Ltd.', 29, 219),
('เกร๊ทเตอร์ฟาร์ม่า', null, null),
('เกร๊กโซ เวลคัม วิทยาศรม', null, null),
('เกร๊กโซสมิทไคล์น', null, null),
('ค็อกซ์', null, null),
('คอนติเนนเติล-ฟาร์ม', null, null),
('เค.บี.', null, null),
('เคนยากุ', null, null),
('จิวบราเดอร์ส', null, null),
('จี.ไอ.เอส. ฟาร์มา', null, null),
('เจริญเภสัชเเล็บ', null, null),
('เเจนเซ่น-ซีเเลก', null, null),
('ซาโนฟี่-ซินเตลาโบ', null, null),
('ซาโนฟี่-อเวนตีส', null, null),
('ซีโนฟาร์ม', null, null),
('ซีฟาม', null, null),
('ซีวา แอนิมัล เฮลธ์', null, null),
('เชอร์เวียร์', null, null),
('ไซอเมริกันฟาร์มาชูติเคิ้ลส์', null, null),
('ดาด้า ฟาร์มาชูติคอล', null, null),
('ดาเบอร์ ฟาร์มา', null, null),
('ถ้วยทองโอสถ', null, null),
('ทาเคดา', null, null),
('ที.ซี.ที', null, null),
('ที.พี. ดรัก แลบบอราทอรี่ส์', null, null),
('ที.เเมน. ฟาร์มา', null, null),
('ที.เอส. โพลีโปรดักส์', null, null),
('ที.โอ. เคมีคอลส์', null, null),
('ที.โอ. ฟาร์ม่า', null, null),
('ที.โอ. เมด', null, null),
('ที.โอ. เเลบ', null, null),
('เท็กซ์เคมีเกิ้ล โปรดักซ์', null, null),
('ไทย พี.ดี. เคมีคอล', null, null),
('ไทยเเจเเปนแลบบอเรเตอรี่ส์', null, null),
('ไทยนครพัฒนา', null, null),
('ไทยเมจิฟาร์มาซิวติคัล', null, null),
('ไทยโอซูก้า', null, null),
('ไทยโอลีฟ', null, null),
('ไท้อันโอสถ', null, null),
('น่ำก๊ก (ตราหัวสิงห์)', null, null),
('นิวเจริญฟาร์มาซูติคอล', null, null),
('นิวยอร์ค เคมีเกิ้ล', null, null),
('นิวไลฟ์ฟาร์ม้า', null, null),
('โนวา เมดิซึน', null, null),
('โนวาร์ตีส', null, null),
('บริสตอล-ไมเยอร์ส สควิบบ์ ไทย', null, null),
('บางกอกเเล็ป เเอนด์ คอสเมติค', 2, 219),
('บี.เจ. (เบญจโอสถ)', null, null),
('บี.เอม. ฟาร์มาซี', null, null),
('บี.เอ็ล.ฮั้ว', null, null),
('บู๊ทส์ เเมนูเเฟคเจอริ่ง', null, null),
('บูรพาโอสถ', null, 219),
('เบสซี่เเอรอน', null, null),
('เบอร์ลินฟาร์มาซูติคอลอินดัสตรี้', null, null),
('แบ็กซ์เตอร์ เมนูเเฟคเจอริ่ง', null, null),
('ไบร์วู๊ดฟาร์มาซูติคอล', null, null),
('ไบโอเนท-เอเชีย', null, null),
('ไบโอเเลป', null, null),
('ปรูฟฟ์', null, null),
('ปัจจุบันโอสถ', null, null),
('ปับลิด ฟาร์มาซูติคอล แลบ', null, null),
('แปซิฟิค เฮลธ์เเคร์', null, null),
('โปรเกรสเเลบ', null, null),
72
('บุคคโลเทรดติ้ง', null, null),
('ชาญกิจเทรดติ้ง', null, null),
('ชินต้าเทรดติ้ง', null, null),
('ชุมชนเภสัชกรรม', null, null),
('เชี่ยวชาญเภสัช', null, null),
('เฉลิมชัยเภสัช', null, null),
('จรูญเภสัช', null, null),
('ขาวละออเภสัช', null, null)